# :file: .travis.yml
#
# :url:  https://travis-ci.org/prjemian/pyRestTable
#
# for advice, see:
#  https://docs.travis-ci.com/user/customizing-the-build#The-Build-Lifecycle

language: python
python:
  - "2.7"
  - "3.5"

before_script:
  - wget http://repo.continuum.io/miniconda/Miniconda2-4.2.12-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - which pip
  - which python
  - which conda
  - conda install --yes coverage docopt lxml
  - pip install coveralls
  - which coveralls

# command to run tests
script:
  - cd $HOME/build/prjemian/pyRestTable/src/qa_qc
  - which coverage
  - coverage run test_unittest.py

after_success:
  - cd $HOME/build/prjemian/pyRestTable/src/qa_qc
  - which coveralls
  - coveralls
