# :file: .travis.yml
#
# :url:  https://travis-ci.org/prjemian/pyRestTable
#
# for advice, see:
#  https://docs.travis-ci.com/user/customizing-the-build#The-Build-Lifecycle

language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install -r requirements.txt

# command to run tests
script:
  - which coverage
  - coverage run --omit=*/site-packages/* tests/test_results.py
  - coverage run -a --omit=*/site-packages/* tests/_version_test.py

after_success:
  - coverage report
  - which coveralls
  - coveralls
