# :file: .travis.yml
#
# :url:  https://travis-ci.org/prjemian/pyRestTable
#
# for advice, see:
#  https://docs.travis-ci.com/user/customizing-the-build#The-Build-Lifecycle

language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install -r requirements.txt

# command to run tests
script:
  - which coverage
  - coverage run --omit=*/site-packages/* src/qa_qc/test_unittest.py

after_success:
  - which coveralls
  - coveralls
