{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name') %}
{% set version = data.get('version') %}
{% set url = data.get('url') %}
{% set description = data.get('description') %}
{% set keywords = data.get('keywords') %}
{% set license = data.get('license') %}

package:
    name: "{{ name|lower }}"
    version: "{{ version }}"

source:
    path: ../

build:
    noarch: python

requirements:

  build:
    - python
    - setuptools

  run:
    - python

test:

    imports:
        - pyRestTable

    commands:
        - python run_test.py

about:
    home: "{{ url }}"
    license_file: src/pyRestTable/LICENSE.txt
    license_family: CC
    license: "{{ license }}"
    summary: "{{ description }}"
    keywords: "{{ keywords }}"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
# https://conda.io/docs/build_tutorials/pkgs.html
