{% set name = "pyRestTable" %}
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set version = data.get('version') %}

package:
    name: "{{ name|lower }}"
    version: "{{ version }}"

source:
    path: ../

build:
    noarch: python

requirements:

  build:
    - python
    - setuptools

  run:
    - python

test:

    imports:
        - pyRestTable

    commands:
        - python run_test.py

about:
    home: https://pyRestTable.readthedocs.io
    license_file: src/pyRestTable/LICENSE.txt
    license_family: CC
    license: Creative Commons Attribution 4.0 International Public License
    summary: 'Format a nice table in reST (reStructuredText ) from Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
# https://conda.io/docs/build_tutorials/pkgs.html
