name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.6
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: anaconda-client-env
        # environment-file: etc/example-environment.yml
    - shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        printenv | sort 

    # - name: Set up Python 3.8
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.8

    # pyRestTable has no environment.yml file at this time
    # - name: Install dependencies
    #   run: |
    #     # $CONDA is an environment variable pointing to the root of the miniconda directory
    #     $CONDA/bin/conda env update --file environment.yml --name base

    - name: Test with pytest
      run: |
        conda install pytest
        $CONDA/bin/pytest
