name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    name: CI py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8']
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-base: false
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        # channels: defaults,conda-forge
        # channel-priority: true
        activate-environment: anaconda-client-env-py-${{ matrix.python-version }}
        environment-file: environment.yml
        mamba-version: "*"
        use-only-tar-bz2: true  # required for caching
    - shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        printenv | sort

    # - name: Install dependencies
    #   run: |
    #     # $CONDA is an environment variable pointing to the root of the miniconda directory
    #     $CONDA/bin/conda env update --file environment.yml --name base
    #     # TODO: Is this redundant?

    - name: Test with pytest
      run: |
        conda install pytest
        $CONDA/bin/pytest tests
